project:
  type: book
  output-dir: docs

book:
  title: "Models"
  author: "andrés castro araújo"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - part: sim-00-intro.qmd
      chapters: 
        - sim-01-schelling.qmd
    - part: net-00-intro.qmd
      chapters: 
        - net-01-diffusion.qmd
        - net-02-blockmodels.qmd
        - net-03-ergm.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [lumen, custom.scss]
    mainfont: Amiri
    monofont: Fira Code
    fontsize: 1em

fig-align: center

editor: visual

code-fold: true

execute:
  echo: true
  freeze: auto


